### ISSUE TITLE
Video Chat

### ISSUE THREAD

**Issue by peishan31** [peishan31/WEcare#20]
A function to communicate with the professionals via online.
- To talk about the illness
- To record their conversation and to use it for future references.
- Use WebRTC

**Comment by linpeishan** [comment]
Done Criteria:
- Video Chat(Remote and Local Video)

**Comment by peishan31** [comment]
Acceptance Criteria:

- Video Chat(Remote and Local Video)
- Recording both remote and local video

**Comment by peishan31** [comment]
Done Criteria:

- Video Chat(Remote and Local Video)
- Recording remote and local video and be able to download them in webm.
